# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9' # ou a versão que seu projeto está rodando
        
    - name: Rodar testes
      run: swift test --enable-code-coverage
      
    - name: Publicar cobertura de código
      uses: codecov/codecov-action@v3
      with:
        files: .build/debug/codecov/*.json
