name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "5.9.0"
      
    - name: Get swift version
      run: swift --version

    - name: Run Tests with Coverage
      run: |
        swift test \
          --enable-code-coverage \
          --parallel

    - name: Convert Coverage to JSON
      run: |
        xcrun llvm-cov export \
          -format="lcov" \
          .build/debug/*Tests.xctest/Contents/MacOS/*Tests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

    - name: Publicar cobertura de código
      uses: codecov/codecov-action@v3
      with:
        token: abd0b2b1-b925-423b-9af1-f572570da17d
        files: .build/debug/codecov/*.json
