name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "5.9.0"
      
    - name: Get swift version
      run: swift --version # Swift 5.1.0
      
    - name: Rodar testes
      run: swift test --enable-code-coverage

    - name: Publicar cobertura de código
      uses: codecov/codecov-action@v3
      with:
        files: .build/debug/codecov/*.json
