name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "5.9.0"
      
    - name: Get swift version
      run: swift --version

    - name: Run Tests with Coverage
      run: |
        swift test \
          --enable-code-coverage \
          --parallel
